{{ if .Values.installRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-admin
rules:
  # Core API group – pods, services, configmaps, secrets, etc.
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

  # apps group – deployments, replicasets, statefulsets, etc.
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]

  # batch – jobs, cronjobs
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]

  # networking – ingress, netpols
  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]

  # autoscaling – HPAs
  - apiGroups: ["autoscaling"]
    resources: ["*"]
    verbs: ["*"]

  # Role a RoleBinding (local RBAC)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["*"]

  # Optional: events
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["*"]
{{ end }}
