{{ if .Values.useDefaultDeployment}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
      {{ if .Values.restartAfterRedeploy }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
      labels:
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: {{ required ".Values.image is required" .Values.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP


        {{- range .Values.sideContainers }}
        - name: {{ .name }}
          image: {{ required ".Values.image is required" $.Values.image }}-{{ .name }}
          imagePullPolicy: {{ .imagePullPolicy | default "Always" }}
          ports:
            - name: {{ .name }}-port
              containerPort: {{ .port }}
        {{- end }}

{{ end }}