{{ if .Values.useDefaultIngress}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}

  annotations:
    {{ if .Values.wwwRedirect }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{ end }}
    {{ if .Values.issueCertificate }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    {{ end }}
spec:
  ingressClassName: nginx
  {{ if .Values.tls }}
  tls:
    - hosts:
        - {{ .Values.host }}
        {{ if .Values.wwwRedirect }}
        - www.{{ .Values.host }}
        {{ end }}
    {{- range .Values.sideContainers }}
        - {{ .name }}-{{ $.Values.host }}
    {{- end }}
        {{ if .Values.tlsSecretName }}
      secretName: {{ .Values.tlsSecretName}}
        {{ else }}
      secretName: {{ .Release.Name }}-tls
      {{ end }}
  {{ end }}
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http

{{- range .Values.sideContainers }}
    - host: {{ .name }}-{{ $.Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  name: {{ .name }}-port
    {{- end }}
{{ end }}