{{ if .Values.basicAuth }}
{{ if and (.Values.basicAuth.username) (.Values.basicAuth.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  auth: {{ (htpasswd .Values.basicAuth.username .Values.basicAuth.password) | b64enc }}
{{ end }}
{{ end }}

{{- range .Values.sideContainers }}
{{ if .basicAuth | default false }}
{{ if and (.basicAuth.username) (.basicAuth.password) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-auth
  labels:
    release: {{ $.Release.Name }}
type: Opaque
data:
  auth: {{ (htpasswd .basicAuth.username .basicAuth.password) | b64enc }}
{{ end }}
{{ end }}
{{- end }}

