---
{{ if .Values.useDefaultService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    release: {{ .Release.Name }}

{{- range .Values.sideContainers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    release: {{ $.Release.Name }}-{{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .name }}-port
      protocol: TCP
      name: {{ .name }}-port
  selector:
    release: {{ $.Release.Name }}-{{ .name }}
{{- end }}
{{ end }}
