---
{{ if .Values.useDefaultService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort}}
      targetPort: http
      protocol: TCP
      name: http
{{- range .Values.sideContainers }}
    - port: {{ .port }}
      targetPort: {{ .name }}-port
      protocol: TCP
      name: {{ .name }}-port
{{- end }}
  selector:
    release: {{ .Release.Name }}
{{ end }}
