apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  {{- $strategy := .Values.strategy }}
  {{- if and (not $strategy) .Values.persistence.enabled }}
  {{- $strategy = dict "type" "Recreate" }}
  {{- end }}
  {{- if $strategy }}
  strategy:
    {{- toYaml $strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: n8n
          image: {{ include "n8n.image" . }}
          imagePullPolicy: {{ include "n8n.imagePullPolicy" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.command }}
          {{- if kindIs "slice" . }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- else }}
          command: ['sh', '-c', {{ . | quote }}]
          {{- end }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{ end }}
          ports:
            - containerPort: 5678
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath | default "/home/node/.n8n" }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default .Release.Name }}
      {{- end }}
