name: Helm Chart Dry Run

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Helm Template Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.2.4

      - name: Run Helm Lint
        run: make helm-lint

      - name: Run Helm Template
        run: make helm-template

      - name: Yaml Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .build
      
      - name: Install kubeconform
        run: |
          go install github.com/yannh/kubeconform/cmd/kubeconform@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run kubeconform
        run: |
          kubeconform -strict -summary -ignore-missing-schemas  .build
